//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartTable
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ProductPrice { get; set; }
        public string ProductQuantity { get; set; }
        public string ProductCategory { get; set; }
        public string TotalPrice { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual CustomerTable CustomerTable { get; set; }
    }
}
